### PR TITLE
Modified to be compatible with NVidia drivers 451.67

### PR DESCRIPTION
**Pull request by GirardiF**
Changed search pattern to be compatible with new NVidia drivers 461.57

### CODE REVIEW

**Comment by riverar** [comment]
Thanks!

**Comment by GirardiF** [comment]
You welcome, waiting eagerly your magic with AMD drivers!

**Comment by riverar** [comment]
@GirardiF Right now, that's on pause as new GPU paravirtualization features in Windows may solve all our problems very soon.

**Comment by GirardiF** [comment]
True, I hope me too that GPU-P will come to Windows Sever 2019 very soon

**Pull request merged**
